---
- name: Join AVD Instances to Active Directory
  hosts: avd_instances
  gather_facts: yes
  tasks:
    - name: Join to domain
      win_domain_membership:
        dns_domain_name: "your.ad.domain"
        domain_admin_user: "{{ domain_admin_user }}"
        domain_admin_password: "{{ domain_admin_password }}"
        domain_ou_path: "OU=AVD,DC=your,DC=ad,DC=domain"  # Optional: Specify the OU path
        state: domain
      register: domain_join

    - name: Reboot if necessary
      ansible.windows.win_reboot:
      when: domain_join.reboot_required