---
- name: Install and Configure AD DS
  hosts: windows
  gather_facts: false
  tasks:
    - name: Install AD DS Role
      ansible.windows.win_feature:
        name: AD-Domain-Services
        state: present
        include_management_tools: true

    - name: Setup Active Directory Controller
      microsoft.ad.domain:
        dns_domain_name: orange.local
        safe_mode_password: password123!
      register: dc_promotion

    - name: Reboot after promotion if required
      ansible.windows.win_reboot:
      when: dc_promotion.reboot_required

    - name: Create Administrator Account
      tags: create_admin
      microsoft.ad.user:
        name: 'administrator'
        password: 'SecurePassword!234'
        state: present
        user_cannot_change_password: true
        password_never_expires: true
        groups:
          set:
            - Domain Admins
            - Enterprise Admins

    - name: Create AD Users
      tags: create_users
      microsoft.ad.user:
        name: "{{ item.name }}"
        password: "{{ item.password }}"
        state: present
        user_cannot_change_password: true
        password_never_expires: true
        groups:
          set:
            - Domain Users
            - Remote Desktop Users
      loop:
        - name: 'user1'
          password: 'Password123!'
        - name: 'user2'
          password: 'Password123!'
        - name: 'user3'
          password: 'Password123!'

    - name: Ensure Temp Directory Exists
      ansible.windows.win_file:
        path: C:\Temp
        state: directory
      tags: install_azure_ad_connect

    - name: Download Azure AD Connect Installer
      ansible.windows.win_get_url:
        url: 'https://download.microsoft.com/download/B/0/0/B00291D0-5A83-4DE7-86F5-980BC00DE05A/AzureADConnect.msi'
        dest: 'C:\Temp\azureadconnect.msi'
      tags: install_azure_ad_connect

    - name: Install Azure AD Connect
      ansible.windows.win_package:
        path: 'C:\Temp\azureadconnect.msi'
        state: present
        arguments: '/qn'
      tags: install_azure_ad_connect

    - name: Configure Azure AD Connect for Basic User Sync
      ansible.windows.win_shell:
        cmd: |
          Import-Module ADSync
          Set-ADSyncScheduler -CustomizedSyncCycleInterval 01:00:00
          Start-ADSyncSyncCycle -PolicyType Initial
      args:
        executable: powershell.exe
      tags: configure_azure_ad_connect

    - name: Check Azure AD Connect Sync Status
      ansible.windows.win_shell:
        cmd: Get-ADSyncScheduler
      register: sync_status
      args:
        executable: powershell.exe
      tags: validate_azure_ad_connect

    - name: Display Azure AD Connect Sync Status
      ansible.builtin.debug:
        var: sync_status.stdout
      tags: validate_azure_ad_connect
