---
- name: Install and Configure AD DS
  hosts: windows
  gather_facts: false
  tasks:
    - name: Install AD DS Role
      ansible.windows.win_feature:
        name: AD-Domain-Services
        state: present
        include_management_tools: true

    - name: Setup Active Directory Controller
      microsoft.ad.domain:
        dns_domain_name: orange.local
        safe_mode_password: password123!
      register: dc_promotion

    - name: Reboot after promotion if required
      ansible.windows.win_reboot:
      when: dc_promotion.reboot_required

    - name: Create Administrator Account
      tags: create_admin
      microsoft.ad.user:
        name: 'administrator'
        password: 'SecurePassword!234'
        state: present
        user_cannot_change_password: true
        password_never_expires: true
        groups:
          set:
            - Domain Admins
            - Enterprise Admins

    - name: Create AD Users
      tags: create_users
      microsoft.ad.user:
        name: "{{ item.name }}"
        password: "{{ item.password }}"
        state: present
        user_cannot_change_password: true
        password_never_expires: true
        groups:
          set:
            - Domain Users
      loop:
        - name: 'user1'
          password: 'Password123!'
        - name: 'user2'
          password: 'Password123!'
        - name: 'user3'
          password: 'Password123!'
