---
- name: Install and Configure AD DS
  hosts: windows
  gather_facts: no
  tasks:
    - name: Install AD DS Role
      win_feature:
        name: AD-Domain-Services
        state: present
        include_management_tools: true

    - name: Setup Active Directory Controller
      microsoft.ad.domain:
        dns_domain_name: orange.local
        safe_mode_password: password123!
      register: dc_promotion

    - name: Reboot after promotion if required
      ansible.windows.win_reboot:
      when: dc_promotion.reboot_required

    - name: Create AD Users
      microsoft.ad.user:
        name: "{{ item.name }}"
        password: "{{ item.password }}"
        state: present
        user_cannot_change_password: yes
        password_never_expires: yes
      loop:
        - name: 'user1'
          password: 'Password123!'
        - name: 'user2'
          password: 'Password123!'
        - name: 'user3'
          password: 'Password123!'
